                                                  Python for Data Science Practical

                                                         Practical - IV
               Name: Amit Vishwakarama                                            Class : SY IT                                          
               Roll No. : S057                                                  Batch : 1
               Date of Assignment : 05/08/26                                    Date/Time of Submission :05/08/26

In [1]:
import numpy as np

A. Write a python code to create Numpy Array.

In [5]:
a = np.array([1,2,3])
print(a)

[1 2 3]


B. Write a python code to demonstrate basic operations on single array. 


In [8]:
print(a+2)
print(a*2)

[3 4 5]
[2 4 6]


C. Write a python code to create array with 10 elements and slice element from 1st to 5th element

In [10]:
b = np.array([1,2,3,4,5,6,7,8,9,10])
print(b[0:5])

[1 2 3 4 5]


D. Write a python code to sort an array alphabetically.


In [13]:
name = np.array(["Shiv","Shiva","Shivaya","Shivam"])
np.sort(name)

array(['Shiv', 'Shiva', 'Shivam', 'Shivaya'], dtype='<U7')

E. Write a python code to create a filter array that will return maximum values from an array.


In [19]:
price = np.array([20890, 3060,45000,4503,5608])
print(price[price>3060])

[20890 45000  4503  5608]
